//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nckh
{
    using System;
    using System.Collections.Generic;
    
    public partial class QL_PD
    {
        public byte ID { get; set; }
        public string Tentb { get; set; }
        public string Tenp { get; set; }
        public string Cp { get; set; }
    }
}
